### ISSUE TITLE
Missing dependencies when building

### ISSUE THREAD

**Issue by ilons** [bigwheels16/AOChatProxy#1]
First of all, thank you for spending time on this project, I appreciated it!
Then, I'd like to apologize in advance, I normally dont build or handle java stuff, so I probably do a bunch of things the wrong way. If this is the cause for my issues, please point it out to me.

When I try to build it, I'm encounter this issue:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.904 s
[INFO] Finished at: 2018-03-10T20:32:57+00:00
[INFO] Final Memory: 14M/306M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aochatproxy: Could not resolve dependencies for project com.jkbff.ao:aochatproxy:jar:2.5: The following artifacts could not be resolved: com.jkbff.ao:tyrlib:jar:1.11, com.jkbff.common:scala-util:jar:1.2: Could not find artifact com.jkbff.ao:tyrlib:jar:1.11 in tyrlib-repo (http://bigwheels16.github.com/TyrLib/maven2/releases) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

The steps I took to reproduce it are (building in docker):
```
docker run --rm -it openjdk:8-slim
apt update \
    && apt upgrade -y --no-install-recommends \
    && apt install -y --no-install-recommends \
        ca-certificates \
        maven \
        git
git clone https://github.com/bigwheels16/AOChatProxy.git build \
    && cd build \
    && mvn clean \
    && mvn package
```

I also tried to build the dependencies manually:
```
docker run --rm -it openjdk:8-slim
apt update \
    && apt upgrade -y --no-install-recommends \
    && apt install -y --no-install-recommends \
        ca-certificates \
        maven \
        git
git clone https://github.com/bigwheels16/TyrLib.git tyrlib \
    && cd tyrlib \
    && mvn clean \
    && mvn package \
    && mvn install:install-file \
        -Dfile=target/tyrlib-1.11.jar \
        -DgroupId=com.jkbff.ao \
        -DartifactId=tyrlib \
        -Dversion=1.11 \
        -Dpackaging=jar \
        -DgeneratePom=true \
    && cd ..
git clone https://github.com/bigwheels16/scala-util.git scala-util \
    && cd scala-util \
    && mvn clean \
    && mvn package \
    && mvn install:install-file \
        -Dfile=target/scala-util-1.2.jar \
        -DgroupId=com.jkbff.common \
        -DartifactId=scala-util \
        -Dversion=1.2 \
        -Dpackaging=jar \
        -DgeneratePom=true\
    && cd ..
```
When I then rebuild the proxy, it works, however, I'm unable to start it, running:
```
java -jar /build/target/AOChatProxy-2.5/lib/aochatproxy-2.5.jar
no main manifest attribute, in /build/target/AOChatProxy-2.5/lib/aochatproxy-2.5.jar
```

**Comment by bigwheels16** [comment]
It looks like you are close, but you can't use `java -jar` to start it since it's not an executable jar.  You do need to install the dependencies like you are doing.  After that, you need to package the AOChatProxy with `mvn package`.  It will create a directory `./target/AOChatProxy-2.5` (or whatever the version is).  You should `cd` into that directory, and then run `./start.sh` and that should start it.

Also, you don't need to manually specify the file to install it for the dependencies, you can just do `mvn install` and it will set all those values for you and put the jars in the local maven repository.

**Comment by ilons** [comment]
Thank you for the hint of mvn install, its a tad more convinient :)

When I've built the proxy, there is no `start.sh`, only a `run.sh`, but creating a config.properties and running it seems to start the proxy.

Thanks for the help!

Do you have any interest in getting a dockerfile for the proxy (which is what I'm creating) to keep in the repo?

**Comment by bigwheels16** [comment]
Oh you're right.  I was meaning to change it to `start.sh` but I guess I haven't done that yet.  In any case, I'm glad you got it working.

And yes, I would definitely be interested in having a Dockerfile in the repo.  Just create a PR for it when it's ready.
